#pragma once

static const char WEB_INDEX_HTML[] =
    "<!doctype html><html><head><meta charset='utf-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>ESP32-CAM</title><style>"
    "body{margin:0;background:#111;color:#eee;font-family:system-ui;text-align:center}"
    "main{max-width:900px;margin:auto;padding:18px;position:relative}"
    "#metrics{display:inline-block;padding:6px 10px;border-radius:6px;"
    "background:#000a;color:#64ff7b;font:600 16px monospace;text-align:right}"
    "img{width:100%;height:auto;background:#222}"
    "button{padding:9px 16px;background:#2878d0;color:#fff;border:0;border-radius:8px;cursor:pointer}"
    ".controls{display:flex;gap:16px;align-items:center;justify-content:center;flex-wrap:wrap;"
    "margin:14px 0;padding:12px;background:#1d1d1d;border-radius:8px}"
    ".controls label{display:flex;align-items:center;gap:8px}"
    ".controls select{padding:6px 10px;background:#292929;color:#eee;border:1px solid #555;border-radius:6px}"
    "a{display:inline-block;margin:16px;padding:10px 18px;background:#2878d0;color:white;"
    "text-decoration:none;border-radius:8px}</style></head><body><main>"
    "<h1>ESP32-CAM Live</h1><div id='metrics'><div id='fps'>--.- FPS</div>"
    "<div id='speed'>-- Kbps</div></div>"
    "<p>RTSP/RTP 低延迟模式：用 VLC 打开 rtsp://192.168.4.1:554/mjpeg/1</p>"
    "<button id='browserVideo'>启动浏览器兼容视频（备用）</button>"
    "<img id='stream' alt='MJPEG stream' style='display:none'>"
    "<div class='controls'><label><input id='autoExposure' type='checkbox'>自动曝光</label>"
    "<label>曝光 <select id='exposure'><option value='100' selected>短（30 FPS）</option>"
    "<option value='300'>中（更亮）</option><option value='600'>长（可能降帧）</option></select></label>"
    "<label>画质 <select id='quality'><option value='30'>流畅</option>"
    "<option value='20' selected>均衡</option><option value='12'>清晰</option></select></label>"
    "<label>分辨率 <select id='resolution'><option value='qvga' selected>流畅 320×240</option>"
    "<option value='cif'>均衡 400×296</option><option value='vga'>清晰 640×480</option></select></label></div>"
    "<p><a href='/snapshot'>Open snapshot</a></p>"
    "</main><script>"
    "const stream=document.getElementById('stream'),streamUrl='http://'+location.hostname+':81/stream';"
    "const browserButton=document.getElementById('browserVideo');let reconnectTimer,browserStreaming=false;"
    "function startStream(){if(!browserStreaming)return;clearTimeout(reconnectTimer);"
    "stream.style.display='block';stream.src=streamUrl+'?t='+Date.now();}"
    "function stopStream(){stream.removeAttribute('src');}"
    "stream.onerror=()=>{if(browserStreaming){clearTimeout(reconnectTimer);"
    "reconnectTimer=setTimeout(startStream,250);}};"
    "browserButton.onclick=()=>{browserStreaming=!browserStreaming;"
    "browserButton.textContent=browserStreaming?'停止浏览器兼容视频':'启动浏览器兼容视频（备用）';"
    "if(browserStreaming)startStream();else{stopStream();stream.style.display='none';}};"
    "const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));"
    "async function updateStats(){try{const r=await fetch('/stats',{cache:'no-store'});"
    "const s=await r.json();document.getElementById('fps').textContent=s.fps.toFixed(1)+' FPS';"
    "document.getElementById('speed').textContent=s.kbps>=1000?"
    "(s.kbps/1000).toFixed(2)+' Mbps':Math.round(s.kbps)+' Kbps';"
    "}catch(e){document.getElementById('fps').textContent='--.- FPS';"
    "document.getElementById('speed').textContent='-- Kbps';}}"
    "const ae=document.getElementById('autoExposure'),ex=document.getElementById('exposure'),"
    "quality=document.getElementById('quality'),resolution=document.getElementById('resolution');"
    "function syncExposureUi(){ex.disabled=ae.checked;}"
    "async function setControl(name,value){const r=await fetch('/control?'+name+'='+encodeURIComponent(value),"
    "{cache:'no-store'});if(!r.ok)throw new Error('control failed');return r.json();}"
    "async function applyAuto(){syncExposureUi();try{await setControl('auto',ae.checked?1:0);}catch(e){}}"
    "async function applyExposure(){try{await setControl('exposure',ex.value);}catch(e){}}"
    "async function applyStreamSetting(name,value,element){element.disabled=true;"
    "if(browserStreaming)stopStream();await sleep(120);try{await setControl(name,value);}catch(e){}"
    "finally{if(browserStreaming)startStream();element.disabled=false;}}"
    "async function loadControls(){try{const r=await fetch('/control',{cache:'no-store'});"
    "const s=await r.json();ae.checked=s.auto;ex.value=s.exposure;quality.value=s.quality;"
    "resolution.value=s.resolution;syncExposureUi();}catch(e){}}"
    "ae.addEventListener('change',applyAuto);ex.addEventListener('change',applyExposure);"
    "quality.addEventListener('change',()=>applyStreamSetting('quality',quality.value,quality));"
    "resolution.addEventListener('change',()=>applyStreamSetting('resolution',resolution.value,resolution));"
    "loadControls();setInterval(updateStats,1000);updateStats();"
    "</script></body></html>";
